name: Binder Badge
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] does not seem to execute code, binder-link seems safely programmed
    types: [opened]

permissions: {}

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@f5d710df1483f19b666dd96aeabbe949a53642c2 # v0.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
